version: '3.8'

services:
  api:
    container_name: api
    image: webapi
    environment:
      - SQLServerConnectionString:${ConnectionStrings__SQLServerConnectionString}
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_Kestrel__Certificates__Default__Path:KestrelSSLCertficate.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password:${password}
    ports:
      - "8080:8080"
    depends_on:
      - db   
    volumes:
    - ./certs/KestrelSSLCertficate.pfx:/app/KestrelSSLCertficate.pfx:ro
  db:
    container_name: teamcollaborationhubDB
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password1*
    ports:
      - "1433:1433"
  cache:
   image: redis:6.2-alpine
   container_name: redis
   ports:
     - "6379:6379"
   volumes:
   - redis-data:/data