version: '3.8'

services:
  api:
    container_name: app
    image: webapi
    environment:
      - SQLServerConnectionString:Server=(localdb)\\MSSQLLocalDB;Database=TeamCollaborationHubDB;Trusted_connection=true;TrustServerCertificate=true;
    ports:
      - "8080:8080"
    depends_on:
      - db   
  db:
    container_name: teamcollaborationhubDB
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password1*
    ports:
      - "1433:1433"