name: Build,Test and Push Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  dotnet-version: "8"

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: .NET setup
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ env.dotnet-version }}
      - name: install dependencies
        run: dotnet restore
      - name: Build project
        run: dotnet build --configuration Release --no-restore
      - name: Run tests ðŸ§ª
        run: dotnet test --no-build --verbosity normal
      - name: Publish for Docker
        run: dotnet publish -c Release -o out

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
            - name: Build and Push Docker Image
              uses: docker/build-push-action@v4
              with:
                context: .TeamcollborationHub.server
                file: ./TeamcollborationHub.server/Dockerfile
                push: true
                tags: ${{ secrets.DOCKER_HUB_USERNAME }}/teamhub:latest